/* 
 * OMDb API
 *
 * This API requires authorization, you can get a free key here: [http://omdbapi.com/apikey.aspx](http://omdbapi.com/apikey.aspx)
 *
 * OpenAPI spec version: 1.0
 * Contact: bfritz@fadingsignal.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISearchParameterApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Returns an array of results for a given title
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="s">Title of movie or series</param>
        /// <param name="y">Year of release (optional)</param>
        /// <param name="type">Return movie or series (optional)</param>
        /// <param name="r">The response type to return (optional)</param>
        /// <param name="page">Page number to return (optional)</param>
        /// <param name="callback">JSONP callback name (optional)</param>
        /// <returns></returns>
        void TitleSearch (string s, int? y = null, string type = null, string r = null, int? page = null, string callback = null);

        /// <summary>
        /// Returns an array of results for a given title
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="s">Title of movie or series</param>
        /// <param name="y">Year of release (optional)</param>
        /// <param name="type">Return movie or series (optional)</param>
        /// <param name="r">The response type to return (optional)</param>
        /// <param name="page">Page number to return (optional)</param>
        /// <param name="callback">JSONP callback name (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> TitleSearchWithHttpInfo (string s, int? y = null, string type = null, string r = null, int? page = null, string callback = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Returns an array of results for a given title
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="s">Title of movie or series</param>
        /// <param name="y">Year of release (optional)</param>
        /// <param name="type">Return movie or series (optional)</param>
        /// <param name="r">The response type to return (optional)</param>
        /// <param name="page">Page number to return (optional)</param>
        /// <param name="callback">JSONP callback name (optional)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task TitleSearchAsync (string s, int? y = null, string type = null, string r = null, int? page = null, string callback = null);

        /// <summary>
        /// Returns an array of results for a given title
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="s">Title of movie or series</param>
        /// <param name="y">Year of release (optional)</param>
        /// <param name="type">Return movie or series (optional)</param>
        /// <param name="r">The response type to return (optional)</param>
        /// <param name="page">Page number to return (optional)</param>
        /// <param name="callback">JSONP callback name (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> TitleSearchAsyncWithHttpInfo (string s, int? y = null, string type = null, string r = null, int? page = null, string callback = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SearchParameterApi : ISearchParameterApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchParameterApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SearchParameterApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchParameterApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SearchParameterApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Returns an array of results for a given title 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="s">Title of movie or series</param>
        /// <param name="y">Year of release (optional)</param>
        /// <param name="type">Return movie or series (optional)</param>
        /// <param name="r">The response type to return (optional)</param>
        /// <param name="page">Page number to return (optional)</param>
        /// <param name="callback">JSONP callback name (optional)</param>
        /// <returns></returns>
        public void TitleSearch (string s, int? y = null, string type = null, string r = null, int? page = null, string callback = null)
        {
             TitleSearchWithHttpInfo(s, y, type, r, page, callback);
        }

        /// <summary>
        /// Returns an array of results for a given title 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="s">Title of movie or series</param>
        /// <param name="y">Year of release (optional)</param>
        /// <param name="type">Return movie or series (optional)</param>
        /// <param name="r">The response type to return (optional)</param>
        /// <param name="page">Page number to return (optional)</param>
        /// <param name="callback">JSONP callback name (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> TitleSearchWithHttpInfo (string s, int? y = null, string type = null, string r = null, int? page = null, string callback = null)
        {
            // verify the required parameter 's' is set
            if (s == null)
                throw new ApiException(400, "Missing required parameter 's' when calling SearchParameterApi->TitleSearch");

            var localVarPath = "?";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (s != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "s", s)); // query parameter
            if (y != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "y", y)); // query parameter
            if (type != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "type", type)); // query parameter
            if (r != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "r", r)); // query parameter
            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter
            if (callback != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "callback", callback)); // query parameter

            // authentication (APIKeyQueryParam) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apikey")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apikey", this.Configuration.GetApiKeyWithPrefix("apikey")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TitleSearch", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                localVarResponse.Content);
        }

        /// <summary>
        /// Returns an array of results for a given title 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="s">Title of movie or series</param>
        /// <param name="y">Year of release (optional)</param>
        /// <param name="type">Return movie or series (optional)</param>
        /// <param name="r">The response type to return (optional)</param>
        /// <param name="page">Page number to return (optional)</param>
        /// <param name="callback">JSONP callback name (optional)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task TitleSearchAsync (string s, int? y = null, string type = null, string r = null, int? page = null, string callback = null)
        {
             await TitleSearchAsyncWithHttpInfo(s, y, type, r, page, callback);

        }

        /// <summary>
        /// Returns an array of results for a given title 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="s">Title of movie or series</param>
        /// <param name="y">Year of release (optional)</param>
        /// <param name="type">Return movie or series (optional)</param>
        /// <param name="r">The response type to return (optional)</param>
        /// <param name="page">Page number to return (optional)</param>
        /// <param name="callback">JSONP callback name (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> TitleSearchAsyncWithHttpInfo (string s, int? y = null, string type = null, string r = null, int? page = null, string callback = null)
        {
            // verify the required parameter 's' is set
            if (s == null)
                throw new ApiException(400, "Missing required parameter 's' when calling SearchParameterApi->TitleSearch");

            var localVarPath = "?";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (s != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "s", s)); // query parameter
            if (y != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "y", y)); // query parameter
            if (type != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "type", type)); // query parameter
            if (r != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "r", r)); // query parameter
            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter
            if (callback != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "callback", callback)); // query parameter

            // authentication (APIKeyQueryParam) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("apikey")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "apikey", this.Configuration.GetApiKeyWithPrefix("apikey")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TitleSearch", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                localVarResponse.Content);
        }

    }
}
